# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maia_gui_v0.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1100, 673)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(670, 10, 221, 171))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 111, 17))
        self.label_4.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.label_sys_ready = QtWidgets.QLabel(self.frame)
        self.label_sys_ready.setGeometry(QtCore.QRect(50, 50, 131, 31))
        self.label_sys_ready.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_sys_ready.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 12pt \"Ubuntu\";")
        self.label_sys_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_ready.setWordWrap(True)
        self.label_sys_ready.setObjectName("label_sys_ready")
        self.label_sys_not_ready = QtWidgets.QLabel(self.frame)
        self.label_sys_not_ready.setGeometry(QtCore.QRect(50, 50, 131, 31))
        self.label_sys_not_ready.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_sys_not_ready.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"font: 12pt \"Ubuntu\";")
        self.label_sys_not_ready.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_not_ready.setWordWrap(True)
        self.label_sys_not_ready.setObjectName("label_sys_not_ready")
        self.label_sys_inprogress = QtWidgets.QLabel(self.frame)
        self.label_sys_inprogress.setGeometry(QtCore.QRect(50, 50, 131, 31))
        self.label_sys_inprogress.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_sys_inprogress.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 12pt \"Ubuntu\";")
        self.label_sys_inprogress.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_inprogress.setWordWrap(True)
        self.label_sys_inprogress.setObjectName("label_sys_inprogress")
        self.label_sys_manual_mode = QtWidgets.QLabel(self.frame)
        self.label_sys_manual_mode.setGeometry(QtCore.QRect(50, 110, 131, 31))
        self.label_sys_manual_mode.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_sys_manual_mode.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 12pt \"Ubuntu\";")
        self.label_sys_manual_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_manual_mode.setWordWrap(True)
        self.label_sys_manual_mode.setObjectName("label_sys_manual_mode")
        self.label_sys_auto_mode = QtWidgets.QLabel(self.frame)
        self.label_sys_auto_mode.setGeometry(QtCore.QRect(50, 110, 131, 31))
        self.label_sys_auto_mode.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_sys_auto_mode.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 12pt \"Ubuntu\";")
        self.label_sys_auto_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_auto_mode.setWordWrap(True)
        self.label_sys_auto_mode.setObjectName("label_sys_auto_mode")
        self.label_sys_inprogress.raise_()
        self.label_sys_auto_mode.raise_()
        self.label_sys_ready.raise_()
        self.label_sys_not_ready.raise_()
        self.label_4.raise_()
        self.label_sys_manual_mode.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(670, 310, 421, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.task_progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.task_progressBar.setGeometry(QtCore.QRect(20, 50, 381, 23))
        self.task_progressBar.setProperty("value", 24)
        self.task_progressBar.setObjectName("task_progressBar")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 81, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 191, 17))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(20, 260, 101, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(120, 260, 51, 17))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(20, 110, 121, 17))
        self.label_13.setObjectName("label_13")
        self.label_current_task = QtWidgets.QLabel(self.frame_2)
        self.label_current_task.setGeometry(QtCore.QRect(20, 120, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_current_task.setFont(font)
        self.label_current_task.setObjectName("label_current_task")
        self.btn_my_button = QtWidgets.QPushButton(self.frame_2)
        self.btn_my_button.setGeometry(QtCore.QRect(40, 180, 131, 51))
        self.btn_my_button.setObjectName("btn_my_button")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 651, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.rviz_main_frame = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.rviz_main_frame.setContentsMargins(0, 0, 0, 0)
        self.rviz_main_frame.setObjectName("rviz_main_frame")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName("tab_3")
        self.frame_6 = QtWidgets.QFrame(self.tab_3)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 631, 551))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(30, 10, 221, 17))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.img_ergonomics = QtWidgets.QLabel(self.frame_6)
        self.img_ergonomics.setGeometry(QtCore.QRect(16, 36, 591, 491))
        self.img_ergonomics.setFrameShape(QtWidgets.QFrame.Box)
        self.img_ergonomics.setText("")
        self.img_ergonomics.setObjectName("img_ergonomics")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(180, 20, 291, 17))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_gripper_ok = QtWidgets.QLabel(self.tab_5)
        self.label_gripper_ok.setGeometry(QtCore.QRect(250, 40, 151, 64))
        self.label_gripper_ok.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_gripper_ok.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_gripper_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gripper_ok.setWordWrap(True)
        self.label_gripper_ok.setObjectName("label_gripper_ok")
        self.label_gripper_fault = QtWidgets.QLabel(self.tab_5)
        self.label_gripper_fault.setGeometry(QtCore.QRect(250, 40, 151, 64))
        self.label_gripper_fault.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_gripper_fault.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_gripper_fault.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gripper_fault.setWordWrap(True)
        self.label_gripper_fault.setObjectName("label_gripper_fault")
        self.label_35 = QtWidgets.QLabel(self.tab_5)
        self.label_35.setGeometry(QtCore.QRect(180, 130, 291, 17))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.frame_9 = QtWidgets.QFrame(self.tab_5)
        self.frame_9.setGeometry(QtCore.QRect(40, 260, 561, 81))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.btn_gripper_grasp = QtWidgets.QPushButton(self.frame_9)
        self.btn_gripper_grasp.setGeometry(QtCore.QRect(110, 30, 131, 41))
        self.btn_gripper_grasp.setObjectName("btn_gripper_grasp")
        self.btn_gripper_release = QtWidgets.QPushButton(self.frame_9)
        self.btn_gripper_release.setGeometry(QtCore.QRect(330, 30, 131, 41))
        self.btn_gripper_release.setObjectName("btn_gripper_release")
        self.label_31 = QtWidgets.QLabel(self.frame_9)
        self.label_31.setGeometry(QtCore.QRect(10, 0, 201, 20))
        self.label_31.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_31.setObjectName("label_31")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 150, 561, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_gripper_req_force = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_gripper_req_force.setFont(font)
        self.label_gripper_req_force.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gripper_req_force.setObjectName("label_gripper_req_force")
        self.gridLayout.addWidget(self.label_gripper_req_force, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_gripper_act_pos = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_gripper_act_pos.setFont(font)
        self.label_gripper_act_pos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gripper_act_pos.setObjectName("label_gripper_act_pos")
        self.gridLayout.addWidget(self.label_gripper_act_pos, 0, 0, 1, 1)
        self.label_gripper_act_force = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_gripper_act_force.setFont(font)
        self.label_gripper_act_force.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gripper_act_force.setObjectName("label_gripper_act_force")
        self.gridLayout.addWidget(self.label_gripper_act_force, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 1, 2, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.tab_5)
        self.frame_10.setGeometry(QtCore.QRect(40, 350, 561, 201))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.btn_gripper_send_params = QtWidgets.QPushButton(self.frame_10)
        self.btn_gripper_send_params.setGeometry(QtCore.QRect(200, 160, 151, 31))
        self.btn_gripper_send_params.setObjectName("btn_gripper_send_params")
        self.label_32 = QtWidgets.QLabel(self.frame_10)
        self.label_32.setGeometry(QtCore.QRect(10, 0, 201, 20))
        self.label_32.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_32.setObjectName("label_32")
        self.sp_deviceMode = QtWidgets.QSpinBox(self.frame_10)
        self.sp_deviceMode.setGeometry(QtCore.QRect(17, 30, 61, 26))
        self.sp_deviceMode.setMinimum(0)
        self.sp_deviceMode.setMaximum(100)
        self.sp_deviceMode.setSingleStep(0)
        self.sp_deviceMode.setProperty("value", 62)
        self.sp_deviceMode.setObjectName("sp_deviceMode")
        self.sp_positionTolerance = QtWidgets.QSpinBox(self.frame_10)
        self.sp_positionTolerance.setGeometry(QtCore.QRect(17, 60, 61, 26))
        self.sp_positionTolerance.setMaximum(2000)
        self.sp_positionTolerance.setProperty("value", 50)
        self.sp_positionTolerance.setObjectName("sp_positionTolerance")
        self.sp_gripForce = QtWidgets.QSpinBox(self.frame_10)
        self.sp_gripForce.setGeometry(QtCore.QRect(17, 90, 61, 26))
        self.sp_gripForce.setMinimum(1)
        self.sp_gripForce.setMaximum(130)
        self.sp_gripForce.setProperty("value", 30)
        self.sp_gripForce.setObjectName("sp_gripForce")
        self.sp_driveVelocity = QtWidgets.QSpinBox(self.frame_10)
        self.sp_driveVelocity.setGeometry(QtCore.QRect(17, 120, 61, 26))
        self.sp_driveVelocity.setMinimum(1)
        self.sp_driveVelocity.setMaximum(100)
        self.sp_driveVelocity.setProperty("value", 50)
        self.sp_driveVelocity.setObjectName("sp_driveVelocity")
        self.sp_shiftPosition = QtWidgets.QSpinBox(self.frame_10)
        self.sp_shiftPosition.setGeometry(QtCore.QRect(310, 60, 61, 26))
        self.sp_shiftPosition.setMinimum(1)
        self.sp_shiftPosition.setMaximum(3000)
        self.sp_shiftPosition.setProperty("value", 1000)
        self.sp_shiftPosition.setObjectName("sp_shiftPosition")
        self.label_33 = QtWidgets.QLabel(self.frame_10)
        self.label_33.setGeometry(QtCore.QRect(80, 30, 131, 20))
        self.label_33.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_10)
        self.label_34.setGeometry(QtCore.QRect(80, 60, 191, 20))
        self.label_34.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.frame_10)
        self.label_36.setGeometry(QtCore.QRect(80, 90, 131, 20))
        self.label_36.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_36.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_10)
        self.label_37.setGeometry(QtCore.QRect(80, 120, 131, 20))
        self.label_37.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_10)
        self.label_38.setGeometry(QtCore.QRect(373, 60, 201, 20))
        self.label_38.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_38.setObjectName("label_38")
        self.sp_basePosition = QtWidgets.QSpinBox(self.frame_10)
        self.sp_basePosition.setGeometry(QtCore.QRect(310, 30, 61, 26))
        self.sp_basePosition.setMinimum(1)
        self.sp_basePosition.setMaximum(3000)
        self.sp_basePosition.setProperty("value", 100)
        self.sp_basePosition.setObjectName("sp_basePosition")
        self.label_39 = QtWidgets.QLabel(self.frame_10)
        self.label_39.setGeometry(QtCore.QRect(373, 30, 201, 20))
        self.label_39.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_39.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_39.setObjectName("label_39")
        self.sp_teachPosition = QtWidgets.QSpinBox(self.frame_10)
        self.sp_teachPosition.setGeometry(QtCore.QRect(310, 90, 61, 26))
        self.sp_teachPosition.setMinimum(1)
        self.sp_teachPosition.setMaximum(3000)
        self.sp_teachPosition.setProperty("value", 2000)
        self.sp_teachPosition.setObjectName("sp_teachPosition")
        self.label_47 = QtWidgets.QLabel(self.frame_10)
        self.label_47.setGeometry(QtCore.QRect(373, 90, 201, 20))
        self.label_47.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_47.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_47.setObjectName("label_47")
        self.sp_workPosition = QtWidgets.QSpinBox(self.frame_10)
        self.sp_workPosition.setGeometry(QtCore.QRect(310, 120, 61, 26))
        self.sp_workPosition.setMinimum(1)
        self.sp_workPosition.setMaximum(3000)
        self.sp_workPosition.setProperty("value", 2600)
        self.sp_workPosition.setObjectName("sp_workPosition")
        self.label_48 = QtWidgets.QLabel(self.frame_10)
        self.label_48.setGeometry(QtCore.QRect(373, 120, 201, 20))
        self.label_48.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_48.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_48.setObjectName("label_48")
        self.sp_gripper_id = QtWidgets.QSpinBox(self.tab_5)
        self.sp_gripper_id.setGeometry(QtCore.QRect(60, 50, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.sp_gripper_id.setFont(font)
        self.sp_gripper_id.setMaximum(2)
        self.sp_gripper_id.setObjectName("sp_gripper_id")
        self.label_49 = QtWidgets.QLabel(self.tab_5)
        self.label_49.setGeometry(QtCore.QRect(60, 30, 111, 20))
        self.label_49.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_49.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_49.setObjectName("label_49")
        self.label_gripper_unknown = QtWidgets.QLabel(self.tab_5)
        self.label_gripper_unknown.setGeometry(QtCore.QRect(250, 40, 151, 64))
        self.label_gripper_unknown.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_gripper_unknown.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"font: 20pt \"Ubuntu\";")
        self.label_gripper_unknown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gripper_unknown.setWordWrap(True)
        self.label_gripper_unknown.setObjectName("label_gripper_unknown")
        self.label_gripper_ok.raise_()
        self.label_gripper_fault.raise_()
        self.layoutWidget.raise_()
        self.label_27.raise_()
        self.label_35.raise_()
        self.frame_9.raise_()
        self.frame_10.raise_()
        self.sp_gripper_id.raise_()
        self.label_49.raise_()
        self.label_gripper_unknown.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 631, 551))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 611, 501))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.layoutErgonomics = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.layoutErgonomics.setContentsMargins(0, 0, 0, 0)
        self.layoutErgonomics.setObjectName("layoutErgonomics")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_7 = QtWidgets.QFrame(self.tab_4)
        self.frame_7.setGeometry(QtCore.QRect(10, 0, 631, 551))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(290, 330, 321, 21))
        self.label_18.setAutoFillBackground(False)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_human_distance = QtWidgets.QLabel(self.frame_7)
        self.label_human_distance.setGeometry(QtCore.QRect(380, 350, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_human_distance.setFont(font)
        self.label_human_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_human_distance.setObjectName("label_human_distance")
        self.label_21 = QtWidgets.QLabel(self.frame_7)
        self.label_21.setGeometry(QtCore.QRect(20, 200, 301, 17))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(150, 40, 301, 17))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.frame_7)
        self.label_25.setGeometry(QtCore.QRect(320, 200, 251, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_saf_scanner_ok = QtWidgets.QLabel(self.frame_7)
        self.label_saf_scanner_ok.setGeometry(QtCore.QRect(110, 230, 131, 64))
        self.label_saf_scanner_ok.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_scanner_ok.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_scanner_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_scanner_ok.setWordWrap(True)
        self.label_saf_scanner_ok.setObjectName("label_saf_scanner_ok")
        self.label_saf_scanner_stop = QtWidgets.QLabel(self.frame_7)
        self.label_saf_scanner_stop.setGeometry(QtCore.QRect(110, 230, 131, 64))
        self.label_saf_scanner_stop.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_scanner_stop.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_scanner_stop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_scanner_stop.setWordWrap(True)
        self.label_saf_scanner_stop.setObjectName("label_saf_scanner_stop")
        self.label_saf_glob_warn = QtWidgets.QLabel(self.frame_7)
        self.label_saf_glob_warn.setGeometry(QtCore.QRect(160, 70, 280, 64))
        self.label_saf_glob_warn.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_glob_warn.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_glob_warn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_glob_warn.setWordWrap(True)
        self.label_saf_glob_warn.setObjectName("label_saf_glob_warn")
        self.label_saf_glob_ok = QtWidgets.QLabel(self.frame_7)
        self.label_saf_glob_ok.setGeometry(QtCore.QRect(160, 70, 280, 64))
        self.label_saf_glob_ok.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_glob_ok.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_glob_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_glob_ok.setWordWrap(True)
        self.label_saf_glob_ok.setObjectName("label_saf_glob_ok")
        self.label_saf_glob_stop = QtWidgets.QLabel(self.frame_7)
        self.label_saf_glob_stop.setGeometry(QtCore.QRect(160, 70, 280, 64))
        self.label_saf_glob_stop.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_glob_stop.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_glob_stop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_glob_stop.setWordWrap(True)
        self.label_saf_glob_stop.setObjectName("label_saf_glob_stop")
        self.label_saf_human_track_ok = QtWidgets.QLabel(self.frame_7)
        self.label_saf_human_track_ok.setGeometry(QtCore.QRect(380, 230, 131, 64))
        self.label_saf_human_track_ok.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_human_track_ok.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_human_track_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_human_track_ok.setWordWrap(True)
        self.label_saf_human_track_ok.setObjectName("label_saf_human_track_ok")
        self.label_saf_human_track_warn = QtWidgets.QLabel(self.frame_7)
        self.label_saf_human_track_warn.setGeometry(QtCore.QRect(380, 230, 131, 64))
        self.label_saf_human_track_warn.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_human_track_warn.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_human_track_warn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_human_track_warn.setWordWrap(True)
        self.label_saf_human_track_warn.setObjectName("label_saf_human_track_warn")
        self.label_saf_human_track_error = QtWidgets.QLabel(self.frame_7)
        self.label_saf_human_track_error.setGeometry(QtCore.QRect(380, 230, 131, 64))
        self.label_saf_human_track_error.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_human_track_error.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_human_track_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_human_track_error.setWordWrap(True)
        self.label_saf_human_track_error.setObjectName("label_saf_human_track_error")
        self.label_ht_fps = QtWidgets.QLabel(self.frame_7)
        self.label_ht_fps.setGeometry(QtCore.QRect(380, 450, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_ht_fps.setFont(font)
        self.label_ht_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ht_fps.setObjectName("label_ht_fps")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(290, 430, 321, 21))
        self.label_23.setAutoFillBackground(False)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_saf_global_unkown = QtWidgets.QLabel(self.frame_7)
        self.label_saf_global_unkown.setGeometry(QtCore.QRect(160, 70, 281, 71))
        self.label_saf_global_unkown.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_global_unkown.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_global_unkown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_global_unkown.setWordWrap(True)
        self.label_saf_global_unkown.setObjectName("label_saf_global_unkown")
        self.label_saf_scanner_unknown = QtWidgets.QLabel(self.frame_7)
        self.label_saf_scanner_unknown.setGeometry(QtCore.QRect(110, 230, 131, 71))
        self.label_saf_scanner_unknown.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_scanner_unknown.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_scanner_unknown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_scanner_unknown.setWordWrap(True)
        self.label_saf_scanner_unknown.setObjectName("label_saf_scanner_unknown")
        self.label_saf_human_track_unknown = QtWidgets.QLabel(self.frame_7)
        self.label_saf_human_track_unknown.setGeometry(QtCore.QRect(380, 230, 131, 71))
        self.label_saf_human_track_unknown.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_saf_human_track_unknown.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"font: 20pt \"Ubuntu\";")
        self.label_saf_human_track_unknown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_saf_human_track_unknown.setWordWrap(True)
        self.label_saf_human_track_unknown.setObjectName("label_saf_human_track_unknown")
        self.label_saf_human_track_error.raise_()
        self.label_saf_glob_stop.raise_()
        self.label_saf_glob_warn.raise_()
        self.label_saf_scanner_stop.raise_()
        self.label_saf_human_track_warn.raise_()
        self.label_saf_human_track_ok.raise_()
        self.label_saf_scanner_ok.raise_()
        self.label_saf_glob_ok.raise_()
        self.label_18.raise_()
        self.label_human_distance.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_25.raise_()
        self.label_ht_fps.raise_()
        self.label_23.raise_()
        self.label_saf_global_unkown.raise_()
        self.label_saf_scanner_unknown.raise_()
        self.label_saf_human_track_unknown.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_6)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 651, 571))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_6, "")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(900, 190, 191, 111))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 151, 17))
        self.label_12.setObjectName("label_12")
        self.label_ergo_bad = QtWidgets.QLabel(self.frame_5)
        self.label_ergo_bad.setGeometry(QtCore.QRect(30, 30, 131, 61))
        self.label_ergo_bad.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_ergo_bad.setStyleSheet("background-color: rgb(237, 212, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_ergo_bad.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ergo_bad.setWordWrap(True)
        self.label_ergo_bad.setObjectName("label_ergo_bad")
        self.label_ergo_ok = QtWidgets.QLabel(self.frame_5)
        self.label_ergo_ok.setGeometry(QtCore.QRect(30, 30, 131, 61))
        self.label_ergo_ok.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_ergo_ok.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 20pt \"Ubuntu\";")
        self.label_ergo_ok.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ergo_ok.setWordWrap(True)
        self.label_ergo_ok.setObjectName("label_ergo_ok")
        self.label_ergo_unknown = QtWidgets.QLabel(self.frame_5)
        self.label_ergo_unknown.setGeometry(QtCore.QRect(30, 30, 131, 61))
        self.label_ergo_unknown.setMaximumSize(QtCore.QSize(16777215, 16777207))
        self.label_ergo_unknown.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"font: 20pt \"Ubuntu\";")
        self.label_ergo_unknown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ergo_unknown.setWordWrap(True)
        self.label_ergo_unknown.setObjectName("label_ergo_unknown")
        self.label_ergo_bad.raise_()
        self.label_12.raise_()
        self.label_ergo_ok.raise_()
        self.label_ergo_unknown.raise_()
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(670, 190, 221, 111))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 76, 17))
        self.label_7.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.btn_manual_req = QtWidgets.QPushButton(self.frame_8)
        self.btn_manual_req.setGeometry(QtCore.QRect(10, 50, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_manual_req.setFont(font)
        self.btn_manual_req.setObjectName("btn_manual_req")
        self.btn_cycle_start = QtWidgets.QPushButton(self.frame_8)
        self.btn_cycle_start.setGeometry(QtCore.QRect(120, 20, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_cycle_start.setFont(font)
        self.btn_cycle_start.setObjectName("btn_cycle_start")
        self.btn_auto_req = QtWidgets.QPushButton(self.frame_8)
        self.btn_auto_req.setGeometry(QtCore.QRect(10, 20, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_auto_req.setFont(font)
        self.btn_auto_req.setObjectName("btn_auto_req")
        self.btn_cycle_stop = QtWidgets.QPushButton(self.frame_8)
        self.btn_cycle_stop.setGeometry(QtCore.QRect(120, 50, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_cycle_stop.setFont(font)
        self.btn_cycle_stop.setObjectName("btn_cycle_stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SoftManBot - System HMI"))
        self.label_4.setText(_translate("MainWindow", "System Status"))
        self.label_sys_ready.setText(_translate("MainWindow", "Ready to start"))
        self.label_sys_not_ready.setText(_translate("MainWindow", "Not ready"))
        self.label_sys_inprogress.setText(_translate("MainWindow", "Cycle in progress"))
        self.label_sys_manual_mode.setText(_translate("MainWindow", "Manual"))
        self.label_sys_auto_mode.setText(_translate("MainWindow", "Automatic"))
        self.label_5.setText(_translate("MainWindow", "Task Status"))
        self.label_6.setText(_translate("MainWindow", "Gobal task progression"))
        self.label_9.setText(_translate("MainWindow", "Total Products"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Current task"))
        self.label_current_task.setText(_translate("MainWindow", "current_task_from_ROS"))
        self.btn_my_button.setText(_translate("MainWindow", "my pushbutton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "System Overview"))
        self.label_17.setText(_translate("MainWindow", "Show image from topic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Task detail view"))
        self.label_27.setText(_translate("MainWindow", "Global status"))
        self.label_gripper_ok.setText(_translate("MainWindow", "Connected"))
        self.label_gripper_fault.setText(_translate("MainWindow", "Error"))
        self.label_35.setText(_translate("MainWindow", "Live data"))
        self.btn_gripper_grasp.setText(_translate("MainWindow", "Execute grasp"))
        self.btn_gripper_release.setText(_translate("MainWindow", "Execute release"))
        self.label_31.setText(_translate("MainWindow", "Gripper test commands"))
        self.label_gripper_req_force.setText(_translate("MainWindow", "-.-"))
        self.label_28.setText(_translate("MainWindow", "Actual position [mm]"))
        self.label_gripper_act_pos.setText(_translate("MainWindow", "-.-"))
        self.label_gripper_act_force.setText(_translate("MainWindow", "-.-"))
        self.label_29.setText(_translate("MainWindow", "Applied force [N]"))
        self.label_30.setText(_translate("MainWindow", "Requested force [N]"))
        self.btn_gripper_send_params.setText(_translate("MainWindow", "Send parameters"))
        self.label_32.setText(_translate("MainWindow", "Gripper parameters"))
        self.label_33.setText(_translate("MainWindow", "deviceMode"))
        self.label_34.setText(_translate("MainWindow", "[mm/100] positionTolerance"))
        self.label_36.setText(_translate("MainWindow", "[%] gripForce"))
        self.label_37.setText(_translate("MainWindow", "[%] driveVelocity"))
        self.label_38.setText(_translate("MainWindow", "[mm/100] shiftPosition"))
        self.label_39.setText(_translate("MainWindow", "[mm/100] basePosition"))
        self.label_47.setText(_translate("MainWindow", "[mm/100] teachPosition"))
        self.label_48.setText(_translate("MainWindow", "[mm/100] workPosition"))
        self.label_49.setText(_translate("MainWindow", "Gripper ID"))
        self.label_gripper_unknown.setText(_translate("MainWindow", "Unknown"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Gripper"))
        self.label_11.setText(_translate("MainWindow", "Ergonomics visualization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ergonomics"))
        self.label_18.setText(_translate("MainWindow", "Estimated operator - robot distance"))
        self.label_human_distance.setText(_translate("MainWindow", "-.- m"))
        self.label_21.setText(_translate("MainWindow", "Safety evaluation from laser scanner"))
        self.label_22.setText(_translate("MainWindow", "Global safety status"))
        self.label_25.setText(_translate("MainWindow", "Human tracking system"))
        self.label_saf_scanner_ok.setText(_translate("MainWindow", "Normal"))
        self.label_saf_scanner_stop.setText(_translate("MainWindow", "Violation detected"))
        self.label_saf_glob_warn.setText(_translate("MainWindow", "Robot speed reduction active"))
        self.label_saf_glob_ok.setText(_translate("MainWindow", "Normal"))
        self.label_saf_glob_stop.setText(_translate("MainWindow", "Safety stop"))
        self.label_saf_human_track_ok.setText(_translate("MainWindow", "Normal"))
        self.label_saf_human_track_warn.setText(_translate("MainWindow", "Human detected"))
        self.label_saf_human_track_error.setText(_translate("MainWindow", "Error"))
        self.label_ht_fps.setText(_translate("MainWindow", "-- fps"))
        self.label_23.setText(_translate("MainWindow", "Tracking performance"))
        self.label_saf_global_unkown.setText(_translate("MainWindow", "Unknown"))
        self.label_saf_scanner_unknown.setText(_translate("MainWindow", "Unknown"))
        self.label_saf_human_track_unknown.setText(_translate("MainWindow", "Unknown"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Safety"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Rich $$$ text box</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Write</span> <span style=\" font-size:14pt;\">what</span> <span style=\" font-weight:600;\">you</span> want!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Credits"))
        self.label_12.setText(_translate("MainWindow", "Ergonomics Analysis"))
        self.label_ergo_bad.setText(_translate("MainWindow", "Not Good"))
        self.label_ergo_ok.setText(_translate("MainWindow", "Good"))
        self.label_ergo_unknown.setText(_translate("MainWindow", "Unknown"))
        self.label_7.setText(_translate("MainWindow", "Commands"))
        self.btn_manual_req.setText(_translate("MainWindow", "Manual"))
        self.btn_cycle_start.setText(_translate("MainWindow", "Start"))
        self.btn_auto_req.setText(_translate("MainWindow", "Auto"))
        self.btn_cycle_stop.setText(_translate("MainWindow", "Stop"))
